### ISSUE TITLE
How can I use it in WinForm?

### ISSUE THREAD

**Issue by FreeVB** [steamcore/TinyHotKey#1]
How can I use it in WinForm?
The following tests did not work properly.

`
public Form1()
        {
            InitializeComponent();
            using var tinyHotKey = new TinyHotKeyInstance();
            using var registration = tinyHotKey.RegisterHotKey(Modifier.Control | Modifier.Alt, Key.D, () =>
            {
                textBox1.Text += ("\r\nCtrl+Alt+D detected");
                Text = "ok";
                return Task.CompletedTask;
            });

            if (!registration.IsRegistered)
            {
                textBox1.Text += ("无法注册热键 Ctrl+Alt+D，可能它已经被其他人使用了？");
                return;
            }
            textBox1.Text += ("你好，按 Ctrl+Alt+D 或按回车退出");
        }
`

**Comment by DavidZidar** [comment]
I just did a quick test and it works fine for me. But it looks like you are creating and instance and then immediately disposing it in the constructor so it will start listening and then immediately stop listening. Save the instance and dispose the instance and the registration when the application is shutting down.

**Comment by FreeVB** [comment]
Still not, I put it on Form1_ Shown The same is true in . Maybe my method is wrong.

**Comment by FreeVB** [comment]
Can you write an example? I tested it again today and even asked GPT to help me write it, but it still doesn't work properly.

**Comment by DavidZidar** [comment]
There is a sample application in the repository, I just added some comments to explain some more.
https://github.com/steamcore/TinyHotKey/blob/master/samples/ConsoleApp/Program.cs

**Comment by FreeVB** [comment]
But this is only for the console and cannot be used in Winform.

**Comment by DavidZidar** [comment]
There are plenty of other hot key packages that are meant to be used with WinForms. This one is meant to be used when you don't want to use WinForms and need to support things such as NativeAOT.

**Comment by FreeVB** [comment]
Does it mean it doesn't support winform?

**Comment by DavidZidar** [comment]
It's completely independent from WinForms or WPF, it has it's own hidden window, message pump and talks directly to the Win32 API.

**Comment by FreeVB** [comment]
Okay, my project type is Winform, so it seems that I can only give up using this library.
