### ISSUE TITLE
c++\cli support?

### ISSUE THREAD

**Issue by nblog** [steamcore/TinyHotKey#2]
I am trying to install "TinyHotKey" using nuget, but the installation fails.
I'm using [c++\cli ](https://learn.microsoft.com/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp)(.net framework 4.8).

**Comment by DavidZidar** [comment]
Hi, I'm not sure what I can do about this. This is a C# library meant to be used by C# applications. Supporting C++ seems pretty involved and not something I have the time for.

**Comment by E021ntox** [comment]
https://github.com/steamcore/TinyHotKey/blob/010b5b4b8d67be82633ce9b4b28d312c5b465ee8/src/TinyHotKey/Key.cs#L172
https://github.com/steamcore/TinyHotKey/blob/010b5b4b8d67be82633ce9b4b28d312c5b465ee8/src/TinyHotKey/Key.cs#L173
https://github.com/steamcore/TinyHotKey/blob/010b5b4b8d67be82633ce9b4b28d312c5b465ee8/src/TinyHotKey/Key.cs#L178

@DavidZidar Typos

**Comment by DavidZidar** [comment]
@E021ntox It's a clone of this class https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/System/Windows/Forms/Input/Keys.cs
